---
argument_specs:
    main:
    	short_description: "Install and configure STIG Manager on your system."
    	description: >
      		Install all required packages, configure required files and manage services.
    	author: Jason Hickey
        options:
            stigman_pkg:
                default: "tar.xz"
                description: "The extention representing the type of file to lookup/download/unpack"
                type: "str"
            stigman_version:
                default: "1.4.12"
                description: "The stig-manager version to install"
                type: "str"
            stigman_archive:
                default: "stig-manager-linux-{{ stigman_version }}.{{ stigman_pkg }}"
                description: "stig-manager install archive filename"
                type: "str"
            stigman_download_url:
                default: "https://github.com/NUWCDIVNPT/stig-manager/releases/download/{{ stigman_version }}/{{ stigman_archive }}"
                description: "Download URL for stig-manager"
                type: "str"
            stigman_installdir:
                default: "{{ stigman_dest }}/stig-manager-{{ stigman_version }}"
                description: "Installation path"
                type: "str"
            stigman_offline_install
                default: false
                description: "Perform an offline install"
                type: "bool"
            stigman_dest:
                default: "/opt"
                description: "Installation root path"
                type: "str"
            stigman_home:
                default: "{{ stigman_installdir }}"
                description: "Installation work directory"
                type: "str"
            stigman_service_user:
                default: "stigman"
                description: "Posix account username"
                type: "str"
            stigman_service_group:
                default: "stigman"
                description: "Posix account group"
                type: "str"
            stigman_service_restart_always:
                default: false
                description: "systemd restart always behavior of service; takes precedence over stigman_service_restart_on_failure if true"
                type: "bool"
            stigman_service_restart_on_failure:
                default: true
                description: "systemd restart on-failure behavior of service"
                type: "bool"
            stigman_service_restartsec:
                default: "10s"
                description: "systemd RestartSec for service"
                type: "str"
            stigman_log_file:
                default: "{{ stigman_home }}/logs/stigman.log"
                type: "str"
            stigman_config_file:
                default: "{{ stigman_home }}/stig-manager.sh"
                description: "File for configuration"
                type: "str"
            stigman_hostname:
                default: "eh-stigman-1"
                description: "hostname of the server"
                type: "str"
         	stigman_http_context:
                default: "/"
                description: "keycloak context path for rest calls. older version uses /auth"
                type: "str"
            stigman_api_port:
                default: 54000
                description: "HTTP port"
                type: "int"
            stigman_health_check_enabled:
                default: true
                description: "If the server should expose health check endpoints"
                type: "bool"
        	stigman_health_check_url_path:
                default: "/api/op/definition?jsonpath=%24.info.version"
                description: "Path to the health check endpoint; scheme, host and stigman_http_context path that will be prepended automatically"
                type: "str"
            stigman_restart_health_check_delay:
                description: "Seconds to let pass before starting healch checks"
                default: 3
                type: 'int'
            stigman_restart_health_check_reries:
                description: "Number of attempts for successful health check before failing"
                default: 5
                type: 'int'
            stigman_api_address:
                default: "0.0.0.0"
                description: "The IP address on which the the API server will listen"
                type: "str"
            stigman_api_max_json_body:
                default: 5242880
                description: "The maximum size in bytes of the request body when content-Type is application/json"
                type: "int"
            stigman_api_max_upload
                default: 1073741824
                description: "The maximum size in bytes of the file uploaded with content-Type multipart/form-data"
                type: "int"
            stigman_api_port:
                default: "54000"
                description: "The TCP port on which the server will listen"
                type: "int"
            stigman_client_api_base:
                default: "./api"
                description: "The base URL for Client requests to the API relative to the sever root at /. Affects: Client"
                type: "str"
            stigman_classification:
                default: "U"
                description: >
					Sets the classification banner, if any. Available values: "NONE" "U" "CUI" "C" "S" "TS" "SCI"
					Affects: API, Client
                type: "str"
            stigman_client_directory:
                default: "./clients"
                description: >
      		       	The location of the web client files, relative to the API source directory. Note that if running source from a clone of 
					the GitHub repository, the client is located at `../../clients` relative to the API directory.
					Affects: API, Client
                type: "str"
            stigman_client_disabled:
                default: false
                description: "Whether to *not* serve the reference web client. Affects: API, Client"
                type: "bool"
            stigman_client_extra_scopes:
                default: []
                description: >
					OAuth2 scopes to request in addition to 
						stig-manager:stig
						stig-manager:stig:read
						stig-manager:collection
						stig-manager:user
						stig-manager:user:read 
						stig-manager:op 
					Some OIDC providers (Okta) generate a refresh token only if the scope "offline_access" is requested
					Affects: API, Client
                type: "list"
            stigman_client_id:
                default: "stig-manager"
                description: "The OIDC clientId of the web client. Affects: Client"
                type: "str"
			stigman_client_oidc_provider
                default: "https://{{ stigman_hostname }}{{ stigman_http_context }}{{ '/' if stigman_http_context | length > 1 else '' }}realms/stigman }}"
                description: >
					Client override of the base URL of the OIDC provider issuing signed JWTs for the API.  
					The string "/.well-known/openid-configuration" will be appended by the client when 
					fetching metadata. affects: Client
                type: "str"  
            stigman_client_scope_prefix:
                default: ""
                description: >
					String used as a prefix for each scope when authenticating to the OIDC Provider.
					Some providers (Azure AD) expect scope requests in the format "api://<application_id>/<scope>", 
					where "api://<application_id>/" is the required prefix. Affects: Client
                type: "str"
            stigman_client_refresh_disabled:
                default: false
                description: "Whether the web client should use a provided refresh token to update the access token. Affects: Client"
                type: "bool"         
            stigman_client_welcome_image:
                default: ""
                description: >
					An image URL that will be rendered in the Home tab Welcome widget. The image will be scaled to a max width or height of 125 pixels - 
					If no alternate image is specified, the seal of the Department of the 
					Navy (the project sponsor)  will be displayed. Affects: Client Appearance
                type: "str"
            stigman_client_welcome_link:
                default: ""
                description: >
					Value of an optional link that will follow the Welcome message in the Home tab Welcome widget.  
					Affects: Client Appearance
                type: "str"
            stigman_client_welcome_message:
                default: ""
                description: "Text that will be displayed in the Home tab Welcome widget. Affects: Client Appearance"
                type: "str"
            stigman_client_welcome_title:
                default: "Support"
                description: "The tile that will be displayed for the custom Home tab Welcome message. Affects: Client Appearance"
                type: "str"
            stigman_db_host:
                default: "localhost"
                description: "The database hostname or IP from to the API server. Affects: API"
                type: "str"
            stigman_db_max_connections:
                default: 25
                description: "The maximum size of the database connection pool. Affects: API"
                type: "int"
            stigman_db_password:
                default: ""
                description: "The password used to login to the database. Affects: API"
                type: "str"
            stigman_db_port:
                default: 3306
                description: "The database TCP port relative to the API server. Affects: API"
                type: "int"
            stigman_db_schema:
                default: "stigman"
                description: "The schema where the STIG Manager object are found. Affects: API"
                type: "str"
            stigman_db_tls_ca_file:
                default: ""
                description: >
					A file/path relative to the API /tls directory that contains the PEM encoded CA certificate used to sign 
					the database TLS certificate. Setting this variable enables TLS connections to the database.
					Affects: API 
                type: "str"
            stigman_db_tls_cert_file:
                default: ""
                description: >
					A file/path relative to the API /tls directory that contains the PEM encoded Client certificate used when authenticating 
					the database client. Additionally requires setting values for "STIGMAN_DB_TLS_CA_FILE" and "STIGMAN_DB_TLS_KEY_FILE". 
					Affects: API
                type: "str"
            stigman_db_tls_key_file
                default: ""
                description: >
					A file/path relative to the API /tls directory that contains the PEM encoded Client private key used when authenticating 
					the database client. Additionally requires setting values for "STIGMAN_DB_TLS_CA_FILE" and "STIGMAN_DB_TLS_CERT_FILE". 
					Affects: API
                type: "str"
            stigman_db_user:
                default: "stigman"
                description: "The user account used to login to the database. Affects: API "
                type: "str"
            stigman_docs_directory:
                default: "./docs"
                description: >
					The location of the documentation files, relative to the API source directory. Note that if running source from a 
					clone of the GitHub repository, the docs are located at `../../docs/_build/html` relative to the API directory.
					Affects: API, documentation"
                type: "str"
            stigman_docs_disabled:
                default: false
                description: >
					Whether to *not* serve the project Documentation. NOTE: If you choose to serve the Client from the API container 
					but not the Documentation, the links do the Docs on the home page will not work.
					Affects: Documentation
                type: "bool"
            stigman_log_level:
                default: 3
                description: >
					Controls the granularity of the generated log output, from 1 to 4. Each level is inclusive of the ones before it. 
					Level 1 - will log only errors
					level 2 - includes warnings
					level 3 - includes status and transaction logs
					level 4 - includes debug-level logs
					Affects: API
                type: "int"
            stigman_log_mode:
                default: "combined"
                description: >
					Controls whether the logs will create one "combined" log entry for http requests that includes both the request 
					and response information; or two separate log entries, one for the request and one for the response, that can 
					be correlated via a generated Request GUID in each entry.
					Affects: API
                type: "str"
            stigman_jwt_email_claim:
                default: "email"
                description: "The access token claim whose value is the user's email address. Affects: API, Client"
                type: "str"
            stigman_jwt_name_claim:
                default: "name"
                description: "The access token claim whose value is the user's full name. Affects: API, Client"
                type: "str"
            stigman_jwt_privileges_claim:
                default: "realm_access.roles"
                description: "The access token claim whose value is the	userâ€™s privileges. Affects: API, Client"
                type: "str"
            stigman_jwt_scope_claim:
                default: "scope"
                description: >
					The access token claim whose value is the user's scopes.Some OIDC Providers (Okta, Azure AD) use the claim "scp" to enumerate scopes.
					Affects: API, Client
                type: "str"
            stigman_jwt_servicename_claim:
                default: "clientId"
                description: "The access token claim whose value is the user's client. cts: API, Client"
                type: "str"
            stigman_jwt_username_claim:
                default: "preferred_username"
                description: "The access token claim whose value is the user's username. Affects: API, Client"
                type: "str"
			stigman_oidc_provider:
				default: "http://localhost:8080/auth/realms/stigman"
                description: >
					The base URL of the OIDC provider issuing signed JWTs for the API.  
					The string "/.well-known/openid-configuration" will be appended when fetching metadata. 
					Affects: API, Client"
                type: "str"
            tigman_swagger_enabled:
                default: false
                description: "Whether to enable the SwaggerUI SPA at /api-docs. Affects: API"
                type: "bool"
            stigman_swagger_oidc_provider:
                default: "{{ stigman_oidc_provider }}"
                description: >
					SwaggerUI override of the base URL of the OIDC provider issuing signed JWTs for the API.  
					The string "/.well-known/openid-configuration" will be appended by the SwaggerUI when fetching metadata.
					Affects: API
                type: "str"
            stigman_swagger_redirect:
                default: "http://localhost:54000/api-docs/oauth2-redirect.html"
                description: "The redirect URL sent by SwaggerUI to the OIDC provider when authorizing. Affects: API"
                type: "str"
            stigman_swagger_server:
                default: "http://localhost:54000/api"
                description: "The API server URL relative to the SwaggerUI. Affects: API"
                type: "str"











